// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aplfmcekmrmcncvzbrat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwbGZtY2VrbXJtY25jdnpicmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODU1NTgsImV4cCI6MjA1OTc2MTU1OH0.XwT0MJYZ8vvukKOE_hBvA28hi-p8lbMCrQPc68hyMrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);